import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [receivedData, setReceivedData] = useState("");
  useEffect(() => {
    if ((window as any)?.ReactNativeWebView) {
      // ensure window.ReactNativeWebView is there, otherwise, web app might crash if is not there
      (window as any).ReactNativeWebView.postMessage("Wayne is coming again");
    }
    window.parent.postMessage(
      {
        message: "WEB_READY",
      },
      "*"
    );
  }, []);

  // MESSAGE EVENT CATCHING
  useEffect(() => {
    const messageCatchEvent = (event: { data: any }) => {
      const messageData = event.data;
      setReceivedData(messageData);
      if (messageData.message === "NATIVE_APP") {
        setReceivedData(messageData.data);
        // alert(messageData.data);
      }
    };
    window.addEventListener("message", messageCatchEvent);

    return () => {
      window.removeEventListener("message", messageCatchEvent);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Data received = &nbsp;
            <code className={styles.code}>{receivedData}</code>
          </p>
          <p>
            Window received = &nbsp;
            <code className={styles.code}></code>
          </p>
        </div>
      </main>
    </>
  );
}
